-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.world_population
(
    world_id smallint NOT NULL,
    "timestamp" timestamp without time zone NOT NULL,
    population_id serial,
    CONSTRAINT "PK_world_population" PRIMARY KEY (population_id),
    CONSTRAINT "AK_Unique_TimestampAndWorld" UNIQUE ("timestamp", world_id)
);

CREATE TABLE IF NOT EXISTS public.zone_population
(
    zone_population_id serial,
    zone_id smallint NOT NULL,
    world_population_id serial NOT NULL,
    CONSTRAINT "PK_zone_population" PRIMARY KEY (zone_population_id),
    CONSTRAINT "AK_UQ_population_zone" UNIQUE (zone_id, world_population_id)
);

CREATE TABLE IF NOT EXISTS public.faction_population
(
    faction_population_id serial,
    faction_id smallint NOT NULL,
    zone_population_id serial NOT NULL,
    team_id smallint NOT NULL,
    CONSTRAINT "PK_faction_population" PRIMARY KEY (faction_population_id),
    CONSTRAINT "AK_UQ_faction_team_zone" UNIQUE (faction_id, zone_population_id, team_id)
);

CREATE TABLE IF NOT EXISTS public.loadout_population
(
    loadout_population_id serial,
    loadout_id smallint NOT NULL,
    faction_population_id serial NOT NULL,
    amount smallint NOT NULL,
    CONSTRAINT "PK_loadout_population" PRIMARY KEY (loadout_population_id),
    CONSTRAINT "AK_UQ_loadout_faction" UNIQUE (faction_population_id, loadout_id)
);

CREATE TABLE IF NOT EXISTS public.outfit
(
    outfit_id integer NOT NULL,
    name character varying,
    last_fetch timestamp without time zone,
    PRIMARY KEY (outfit_id)
);

CREATE TABLE IF NOT EXISTS public.character_session
(
    character_id integer NOT NULL,
    outfit_id integer,
    session_start timestamp without time zone NOT NULL,
    session_end timestamp without time zone,
    character_session_id integer NOT NULL,
    PRIMARY KEY (character_session_id),
    CONSTRAINT "AK_UQ_Session" UNIQUE (character_id, session_start)
);

CREATE TABLE IF NOT EXISTS public."character"
(
    character_id integer NOT NULL,
    name character varying,
    last_update timestamp without time zone,
    PRIMARY KEY (character_id)
);

CREATE TABLE IF NOT EXISTS public.faction
(
    faction_id smallint NOT NULL,
    name character varying,
    description character varying,
    last_update timestamp without time zone,
    CONSTRAINT "PK_faction" PRIMARY KEY (faction_id)
);

CREATE TABLE IF NOT EXISTS public.zone
(
    zone_id smallint NOT NULL,
    name character varying,
    description character varying,
    last_update timestamp without time zone,
    PRIMARY KEY (zone_id)
);

CREATE TABLE IF NOT EXISTS public.world
(
    world_id smallint NOT NULL,
    name character varying,
    description character varying,
    last_update timestamp without time zone NOT NULL,
    CONSTRAINT "PK_world" PRIMARY KEY (world_id)
);

CREATE TABLE IF NOT EXISTS public.loadout
(
    loadout_id smallint NOT NULL,
    name character varying,
    description character varying,
    last_update timestamp without time zone,
    CONSTRAINT "PK_loadout" PRIMARY KEY (loadout_id)
);

ALTER TABLE IF EXISTS public.world_population
    ADD CONSTRAINT "FK_world_population_world" FOREIGN KEY (world_id)
    REFERENCES public.world (world_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.zone_population
    ADD CONSTRAINT "FK_zone_population_world_population" FOREIGN KEY (world_population_id)
    REFERENCES public.world_population (population_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.zone_population
    ADD CONSTRAINT "FK_zone_population_zone" FOREIGN KEY (zone_id)
    REFERENCES public.zone (zone_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.faction_population
    ADD CONSTRAINT "FK_faction_zone_population" FOREIGN KEY (zone_population_id)
    REFERENCES public.zone_population (zone_population_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.faction_population
    ADD CONSTRAINT "FK_faction_population_faction" FOREIGN KEY (faction_id)
    REFERENCES public.faction (faction_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.faction_population
    ADD CONSTRAINT "FK_faction_population_faction_team" FOREIGN KEY (team_id)
    REFERENCES public.faction (faction_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.loadout_population
    ADD CONSTRAINT "FK_loadout_faction" FOREIGN KEY (faction_population_id)
    REFERENCES public.faction_population (faction_population_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.loadout_population
    ADD CONSTRAINT "FK_loadout_population_loadout" FOREIGN KEY (loadout_id)
    REFERENCES public.loadout (loadout_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.character_session
    ADD CONSTRAINT "FK_character_session_outfit" FOREIGN KEY (outfit_id)
    REFERENCES public.outfit (outfit_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.character_session
    ADD CONSTRAINT "FK_character_session_character" FOREIGN KEY (character_id)
    REFERENCES public."character" (character_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;

END;