version: "3.1"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../../niumside-database.sql:/docker-entrypoint-initdb.d/niumside-database.sql
    restart: unless-stopped

  pop-tracker:
    image: ghcr.io/brakenium/niumside-poptracker
    depends_on:
      - db
    volumes:
      - ./config.yaml:/usr/src/niumside-poptracker/config/local.yaml
    restart: unless-stopped
